// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/eogo-dev/eogo/internal/app"
	"github.com/eogo-dev/eogo/internal/infra/config"
	"github.com/eogo-dev/eogo/internal/infra/database"
	"github.com/eogo-dev/eogo/internal/infra/email"
	"github.com/eogo-dev/eogo/internal/infra/jwt"
	"github.com/eogo-dev/eogo/internal/modules/permission"
	"github.com/eogo-dev/eogo/internal/modules/user"
)

// Injectors from wire.go:

// InitApplication initializes the entire application with all dependencies.
// This is the single entry point for Wire DI.
func InitApplication() (*app.Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	service := jwt.NewService(configConfig)
	emailService := email.NewService(configConfig)
	repository := user.NewRepository(db)
	userService := user.NewService(repository, service)
	handler := user.NewHandler(userService)
	permissionRepository := permission.NewRepository(db)
	permissionService := permission.NewService(permissionRepository)
	permissionHandler := permission.NewHandler(permissionService)
	handlers := &app.Handlers{
		User:       handler,
		Permission: permissionHandler,
	}
	application := &app.Application{
		Config:       configConfig,
		DB:           db,
		JWTService:   service,
		EmailService: emailService,
		Handlers:     handlers,
	}
	return application, nil
}
