// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/eogo-dev/eogo/internal/modules/permission"
	"github.com/eogo-dev/eogo/internal/modules/user"
	"github.com/eogo-dev/eogo/internal/platform/config"
	"github.com/eogo-dev/eogo/internal/platform/jwt"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitApp creates App with all dependencies wired
func InitApp(db *gorm.DB) (*App, error) {
	userRepositoryImpl := user.NewRepository(db)
	configConfig := config.MustLoad()
	service := jwt.NewService(configConfig)
	userServiceImpl := user.NewService(userRepositoryImpl, service)
	handler := user.NewHandler(userServiceImpl)
	repositoryImpl := permission.NewRepository(db)
	serviceImpl := permission.NewService(repositoryImpl)
	permissionHandler := permission.NewHandler(serviceImpl)
	app := &App{
		User:       handler,
		Permission: permissionHandler,
	}
	return app, nil
}

// wire.go:

// App holds all initialized handlers
type App struct {
	User       *user.Handler
	Permission *permission.Handler
}
